### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by kphillisjr**
This is a small series of compilation fixes for slightly older compilers.

### CODE REVIEW

**Comment by mjansson** [comment]
I think was also fixed in the x86 changes in #156

**Comment by kphillisjr** [comment]
I just had a chance to test the changes in #156. 

* This does address the changes found in commit 4d81e49 seeing as how this commit was about addressing the lack of first class heaps on default builds.

* This **does not fix** the change addressed in commit 7523f9a. The change in this commit is due to the fact that c++ compilers are not required to define _Static_assert. However compiler supporting C++ 2011 or newer should support static_assert instead ( see: https://en.cppreference.com/w/cpp/language/static_assert ). For reference on Visual Studio See (https://docs.microsoft.com/en-us/cpp/cpp/static-assert?view=vs-2019 ), and this should work on Visual Studio 2015 or newer.

**Comment by mjansson** [comment]
Line 117 in rpmalloc.c should take care of the _Static_assert on ms compilers - https://github.com/mjansson/rpmalloc/blob/886245b464e70f3339deaa8dfbbe1d9e383b3ad3/rpmalloc/rpmalloc.c#L117

**Comment by kphillisjr** [comment]
The commit 7523f9a is fixes for changes made to rpmalloc/malloc.c made by pull #105  This file does not include rpmalloc/rpmalloc.h nor rpmalloc/rpmalloc.c.

Code causing compile issues found on line 17 to line 26 in rpmalloc/malloc.c... Note that ```C
_Static_assert ``` and ```size_t``` are assumed to be defined.

```
#ifndef ARCH_64BIT
#  if defined(__LLP64__) || defined(__LP64__) || defined(_WIN64)
#    define ARCH_64BIT 1
_Static_assert(sizeof(size_t) == 8, "Data type size mismatch");
_Static_assert(sizeof(void*) == 8, "Data type size mismatch");
#  else
#    define ARCH_64BIT 0
_Static_assert(sizeof(size_t) == 4, "Data type size mismatch");
_Static_assert(sizeof(void*) == 4, "Data type size mismatch");
#  endif
```

**Comment by mjansson** [comment]
Note that malloc.c is not meant to be compiled directly, It is included in rpmalloc.c if overloading of standard malloc/free new/delete is enabled.

This enables the use of aliasing/interposing on platforms that support it.

**Pull request closed without merging**
