### PR TITLE
Modern CMake build system

### LINKED ISSUE #224: Modern CMake build system
I think this is an impressive library, however its build tooling usage makes it difficult to use.

I would like to introduce **modern** CMake to the project and I have a sample [here](https://github.com/friendlyanon/cxx-static-shared-example) which shows what exactly would that look like. I see #159 however that PR is pretty much unusable and doesn't provide everything specified by the project's README.

* Using CMake would allow some of the platform dependant macro stuff in `rpmalloc.h` to be moved into the build system.
* Using CMake would allow trivial packaging of the library to be distributed by distros or general reuse.

Before I start working on a PR, I would like to know if you prefer to keep the old build files to provide a transition period for users of this library? If yes, then my PR won't touch those files.

### PR DESCRIPTION
**Pull request by friendlyanon**
Fixes #224  
Subsumes #159

* Moved things around a little so CMake can be better facilitated.
* Renamed defines to be named consistently with a `RPMALLOC_` prefix and not cause name collision in CMake.
* Componentized the library, which makes package maintainers' life easier and enables trivial packaging (`librpmalloc` and `librpmalloc-dev` packages coming soon?).
* Fixed some actual bugs, like the absence of `_GNU_SOURCE` causing undefined symbol errors.
* Made members of the statistics struct actually conditional as the comments were suggesting. This is definitely a breaking change deserving a major version bump. If that is not desirable at this time, let me know and I'll revert those changes.

The main test runs fine on both Windows and Ubuntu, however I could not figure out how to properly preload the overload test to run that. I tried everything and gdb always showed me that a call to `malloc` goes to libc instead of the override.  
I left the `overload_test` out of the "all" target, but it can always be run by adding `--target overload_test` to the build command of the tests.

I would also like to add a GitHub Actions workflow to have CI running for this project, but maybe that's after someone figured out how to run the override test to begin with or after this PR is merged.

### CODE REVIEW

**Comment by mjansson** [comment]
I am personally not interested in maintaining or using a CMake build system, so don't remove the current one.

Also, the rpmalloc source is made so it can easily be inserted in other build systems, so you cannot assume things like BUILD_* are defined.

**Comment by friendlyanon** [comment]
I see, the config options that can be set from the build system would still need to be separated to easily put them into the headers.

**Comment by friendlyanon** [comment]
Another thing about the config headers: would you want distribution packages to have both public (accessible from rpmalloc.h) and private (defines that can be overridden in rpmalloc.c) installed? There are a lot of knobs to turn in rpmalloc and it might be a good idea to let developers consuming the library from a system installation to introspect on the values used to build the library.

**Comment by mjansson** [comment]
I've decided not to include secondary build systems into the repo, the basic idea of the source code is that should be easy to drop into any codebase instead of building separately. The docs will be updated to reflect this. Thank you for the PR though!

**Pull request closed without merging**
