### PR TITLE
fix: always load memory_map_granularity from system config

### PR DESCRIPTION
**Pull request by FujiZ**
Setting memory_map_granularity directly from user-specified page_size
may cause assersion failure in _rpmalloc_mmap_os(), because the ptr
returned from mmap() are only guaranteed to be aligned to system page
boundary.

After applying this fix, test_large_pages() will pass.

### CODE REVIEW

**Comment by mjansson** [comment]
This certainly makes sense when using the system mmap to map more virtual memory, however it would need to take a custom mmap into account to use the configured size in that case.

I can take a shot at updating the PR for this if you want.

**Comment by FujiZ** [comment]
I'd be grateful if you could help fixing this issue :)

**Comment by FujiZ** [comment]
I noticed that `_memory_map_granularity` is not exported to users and is only used in default memory map & unmap operations. So maybe it has nothing to do with the custom mmap operations?

**Comment by mjansson** [comment]
I had a proper look at this now, and you are indeed correct that the map granularity is only used for the OS default path (even commented as such).

However, it seems to me your patch slightly changes the logic in the setup, so I took the liberty of changing it to keep the current intent of the code.

I also noticed a regression when using huge pages from my last change where the number of spans stored in each heap reserve would swallow a whole huge page, which was not the intention.

All in all, check out #242 and see if it solves your problem in the same way your PR does

**Comment by FujiZ** [comment]
I think #242 solves the problem, thanks!

**Comment by mjansson** [comment]
Thanks, I've merged it, let me know if you run into any more issues

**Pull request closed without merging**
