### PR TITLE
TLS arm asm update, bits clear of tid

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by mjansson** [comment]
Why would the low 2 bits of the thread id register value need to be cleared?

**Comment by devnexen** [comment]
Sorry I did not complete the necessary change, on ARM (normally for 64 bits too but I do not have the related hardware yet), the control block is in the first slot.

**Comment by mjansson** [comment]
Still, wouldn't the pointer to the control block suffice? As it is not really the thread ID we're interested in, just something that is unique for the thread and doesn't change over the lifetime of the thread.

**Comment by devnexen** [comment]
That s a good point I must admit, I m being a bit "pedantic" for no added value.

**Pull request closed without merging**
