### PR TITLE
clang: Disable reserved-identifer warning

### PR DESCRIPTION
**Pull request by sgraham**
Possible fix for #245.

### CODE REVIEW

**Comment by mjansson** [comment]
Instead of putting it in the build setup, I think it would be better to have as a #pragma in rpmalloc.c (there are already a few) in order to make the code self contained.

#pragma clang diagnostic ignored "-Wreserved-identifier"

**Comment by sgraham** [comment]
Makes sense, done. (I saw there was some in both places but I wasn't sure what the rationale for one place or the other was.)

**Comment by digit-google** [comment]
Any reason not to submit this? For the record, this is impacting the GN build tool which links to rpmalloc to _significantly_ speed up its operations (e.g. from 30s to 22s). Unfortunately, we had to disable this due to the issue, see https://gn-review.googlesource.com/c/gn/+/11720).

We can work with a local patch if more changes are necessary in this pull request, but we'd prefer to use upstream directly :-)

**Comment by mjansson** [comment]
I just haven’t had time to verify this myself yet that it doesn’t interfere with builds using older clang versions.

**Comment by mjansson** [comment]
It seems the pragma has to be surrounded with

#if __has_warning("-Wreserved-identifier")
#pragma clang diagnostic ignored "-Wreserved-identifier"
#endif

Or older clang versions will warn about the unknown warning

**Comment by digit-google** [comment]
Thanks for verifying, and providing the necessary fix! I hope Scott can update his pull request (I believe he's on vacation right now). If not, I'd be happy to provide my own PR, but we've finally applied a local patch on our side, so there is no rush.

Thanks again for rpmalloc!

**Comment by mjansson** [comment]
I did the change and merged #249

**Pull request closed without merging**
