### PR TITLE
macOS: tagging our anonymous page.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by mjansson** [comment]
Is the tagging needed? Also, seems it should use the VM_MAKE_TAG macro instead of explicit bitshift

**Comment by devnexen** [comment]
Not necessary but just nice to have if you want to monitor with vmmap. Yes in fact I did the bitshift just to avoid the header inclusion but I can change that, np.

**Comment by mjansson** [comment]
Also, you changed the tag to 127, what was the reasoning behind that? The man page for mmap says "Users are encouraged to use tags between 240 and 255" as your comment also says

**Comment by devnexen** [comment]
True but as mentioned in the commit message, it s due to bit shit compilation flag which makes fail the build.

**Comment by devnexen** [comment]
Note that officially number are taken up to 98, LLVM sanitizers had taken 99.

**Comment by mjansson** [comment]
I suggest 

`int fd = (int)VM_MAKE_TAG(240U);`

in order to follow the guidelines

**Comment by mjansson** [comment]
Also, please remove the comments, I'll put the tag in the documentation instead

**Comment by mjansson** [comment]
Sorry for being a pita, but change the tag to 240U as well (with the explicit types and cast it will not generate a compiler warning)

**Comment by devnexen** [comment]
alright then :-)

**Comment by mjansson** [comment]
Thanks!

**Pull request merged**
